version: "3.9"
services:
  keycloak:
    image: jboss/keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: keycloak
    ports:
      - "8000:8080"
#    volumes:
#      - ./target/tmp:/tmp
